import { z } from 'zod';

/**
 * The pieces every request schema is built out of.
 *
 * These live here rather than in the api because the client validates against
 * the same objects before it sends anything. One definition means the two
 * cannot drift, and a field the server would refuse is a field the client
 * refuses first, offline, without a round trip to find out.
 */

/** An identifier, always a UUID version 7 generated by whoever made the row. */
export const idSchema = z.uuid();

/** A path parameter that is an id and nothing else. */
export const idParamSchema = z.strictObject({ id: idSchema });

/**
 * A moment in time, as an ISO 8601 string with an offset, parsed into a Date.
 *
 * The offset is required. A timestamp without one has to be interpreted
 * against somebody's idea of local time, and the two ends of this wire are in
 * different places by design.
 */
export const instantSchema = z.iso.datetime({ offset: true }).transform((value) => new Date(value));

/** A version number from the user's counter. */
export const revisionSchema = z.coerce.number().int().min(0);

/** How many rows a list endpoint may return at once. */
export const DEFAULT_PAGE_SIZE = 50;
export const MAX_PAGE_SIZE = 200;

export const limitSchema = z.coerce.number().int().min(1).max(MAX_PAGE_SIZE);

/**
 * Where to carry on from.
 *
 * A cursor rather than an offset, because an offset skips rows when something
 * ahead of it is deleted between two pages, and the deck being edited while it
 * is being read is the normal case rather than the odd one.
 */
export const cursorSchema = z.string().min(1).max(200);

/** The shape every list endpoint answers with. */
export function pageOf<T extends z.ZodType>(item: T) {
  return z.object({
    items: z.array(item),
    /** Absent when there is nothing after this page. */
    nextCursor: z.string().optional(),
  });
}

/** Text a person typed into a name field. */
export const nameSchema = z.string().trim().min(1).max(200);

/** A tag on a note. */
export const tagSchema = z.string().trim().min(1).max(60);
