import { z } from 'zod';

import { ratingSchema } from '../rating.js';

import { cardSchema, cardStateSchema } from './cards.js';
import { idSchema, instantSchema } from './common.js';

/**
 * Answering a card. The busiest endpoint there is, and the one with the most
 * ways to go wrong.
 *
 * Three things shape this schema:
 *
 * The id comes from the client. That is what makes a retry harmless: a phone
 * that loses signal after sending and before hearing back will send again, and
 * the second arrival has to be recognised as the same answer rather than
 * counted twice. An id the server generated could not do that.
 *
 * `computed` is optional and is never stored. The client works out the new card
 * state locally, because that is what makes the app work offline and feel
 * instant. The server works it out again and keeps its own. Sending the
 * client's version along is useful only as a comparison: when the two disagree,
 * the answer comes back with a flag telling the client to fetch that card
 * again.
 *
 * `reviewedAt` comes from a device whose clock is not ours. It is clamped
 * rather than trusted.
 */

/** The size of the biggest plausible answer, an hour, to catch a stuck timer. */
const MAX_DURATION_MS = 60 * 60 * 1000;

export const submitReviewSchema = z.strictObject({
  /** Generated by the client. Sending the same one twice changes nothing. */
  id: idSchema,
  cardId: idSchema,
  rating: ratingSchema,
  reviewedAt: instantSchema,
  durationMs: z.number().int().min(0).max(MAX_DURATION_MS).default(0),
  /**
   * What the client made of the answer. Compared, never stored.
   *
   * A modified client could put any number it liked here. That is exactly why
   * the server recomputes: the worst this field can do is trigger a resync of
   * one card.
   */
  computed: z
    .strictObject({
      state: cardStateSchema,
      stability: z.number().positive().nullable(),
      difficulty: z.number().min(1).max(10).nullable(),
      due: instantSchema,
    })
    .optional(),
});

/** A phone coming back from a session with no network sends the lot. */
export const submitReviewBatchSchema = z.strictObject({
  reviews: z.array(submitReviewSchema).min(1).max(500),
});

export const reviewResultSchema = z.object({
  id: idSchema,
  cardId: idSchema,
  /** The card as the server left it. Always the server's own computation. */
  card: cardSchema,
  /** False when this id had already been recorded and nothing changed. */
  applied: z.boolean(),
  /**
   * True when the client's own computation disagreed with the server's beyond
   * rounding. The client should fetch this card again rather than keep what it
   * has.
   */
  resync: z.boolean(),
  /** True when `reviewedAt` was in the future and was pulled back to now. */
  clamped: z.boolean(),
});

export const reviewBatchResultSchema = z.object({
  results: z.array(reviewResultSchema),
  /**
   * Answers that had nowhere to land, usually because the card was deleted on
   * another device while this one was offline.
   *
   * Reported rather than thrown. A phone coming back from a week away should
   * not be unable to sync any of its two hundred answers because one of them
   * points at a card that has since gone.
   */
  skipped: z.array(z.object({ id: idSchema, cardId: idSchema })),
  /** The user's version counter after the batch, for the sync cursor. */
  revision: z.number().int(),
});

export type SubmitReviewBody = z.infer<typeof submitReviewSchema>;
export type SubmitReviewBatchBody = z.infer<typeof submitReviewBatchSchema>;
export type ReviewResult = z.infer<typeof reviewResultSchema>;
export type ReviewBatchResult = z.infer<typeof reviewBatchResultSchema>;
