-- The deck a card belongs to, copied from its note.
--
-- Duplication, added after measuring what it buys on fifty thousand cards:
-- "what is due in this folder" 7.25 ms -> 2.36 ms, and the counts behind the
-- library tree 43.9 ms -> 17.5 ms. Both stop joining through notes.
--
-- Generated by drizzle-kit, then edited to fill the column before making it
-- required. The generated version adds a NOT NULL column in one statement,
-- which fails the moment the table has a row in it.

ALTER TABLE "cards" ADD COLUMN "deck_id" uuid;--> statement-breakpoint

UPDATE "cards" SET "deck_id" = "notes"."deck_id"
	FROM "notes" WHERE "notes"."id" = "cards"."note_id";--> statement-breakpoint

ALTER TABLE "cards" ALTER COLUMN "deck_id" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "cards" ADD CONSTRAINT "cards_deck_id_decks_id_fk" FOREIGN KEY ("deck_id") REFERENCES "public"."decks"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "cards_user_deck_due_idx" ON "cards" USING btree ("user_id","deck_id","due") WHERE "cards"."deleted_at" is null;--> statement-breakpoint
CREATE INDEX "cards_user_deck_idx" ON "cards" USING btree ("user_id","deck_id") WHERE "cards"."deleted_at" is null;
